import turtle
import time

turtle.Turtle()
window = turtle.Screen()
window.setup(width=1.0, height=1.0, startx=0, starty=0)
turtle.pensize(1)
turtle.shape("turtle")
turtle.hideturtle()

def firstPage():
  window.bgcolor('royalblue3')
  turtle.color('firebrick1')
  turtle.penup()
  turtle.goto(0,100)
  turtle.pendown()
  turtle.write("CapStone Project", font=
("Arial",30,'italic'),align='center')
  turtle.right(90)
  turtle.penup()
  turtle.fd(50)
  turtle.write("Capricorn Constellation", font=
("Arial",30,'italic'),align='center')
  turtle.penup()
  turtle.fd(50)
  turtle.pendown()
  turtle.write("Muhammad Qureshi", font=
("Arial",30,'italic'),align='center')
firstPage()
time.sleep(5)
turtle.clear()

def secondPage():
  turtle.color('white')
secondPage()
time.sleep(5)
window.clear()


def thirdPage():
  turtle.bgcolor('white')
  turtle.color('black')
  turtle.penup()
  turtle.goto(0,0)
  turtle.dot(12)
  turtle.write("   Armus")
  turtle.pendown()
  turtle.penup()
  turtle.goto(150,180)
  turtle.pendown()
  turtle.dot(12)
  turtle.write("ALGIEDI")
  turtle.right(330)
  turtle.back(20)
  turtle.dot(10)
  turtle.write("--------ALSHAT")
  turtle.back(160)
  turtle.dot(12)
  turtle.write("DORSUM")
  turtle.right(30)
  turtle.back(120)
  turtle.dot(12)
  turtle.write("NASHIRA")
  turtle.right(10)
  turtle.back(40)
  turtle.dot(12)
  turtle.write("DENEB ALGEDI")
  turtle.right(240)
  turtle.back(50)
  turtle.dot(8)
  turtle.right(305)
  turtle.back(20)
  turtle.dot(12)
  turtle.write("CASTRA")
  turtle.right(30)
  turtle.back(100)
  turtle.dot(12)
  turtle.write("MARAKK")
  turtle.right(340)
  turtle.back(120)
  turtle.dot(12)
  turtle.write("BATEN ALGIEDI")
  turtle.right(270)
  turtle.back(40)
  turtle.dot(8)
  turtle.right(356)
  turtle.back(175)
  turtle.dot(10)
  turtle.write("DABIH")
  turtle.right(360)
  turtle.back(60)

thirdPage()
time.sleep(5)
window.clear()

def fourthPage():
  turtle.bgcolor('black')
  turtle.color('white')
  time.sleep(1)
  turtle.penup()
  turtle.goto(0,0)
  turtle.dot(12)
  turtle.write("   Armus")
  turtle.penup()
  turtle.goto(150,180)
  turtle.dot(12)
  turtle.write("ALGIEDI")
  turtle.right(330)
  turtle.back(20)
  turtle.dot(10)
  turtle.write("--------ALSHAT")
  turtle.back(160)
  turtle.dot(12)
  turtle.write("DORSUM")
  turtle.right(30)
  turtle.back(120)
  turtle.dot(12)
  turtle.write("NASHIRA")
  turtle.right(10)
  turtle.back(40)
  turtle.dot(12)
  turtle.write("DENEB ALGEDI")
  turtle.right(240)
  turtle.back(50)
  turtle.dot(8)
  turtle.right(305)
  turtle.back(20)
  turtle.dot(12)
  turtle.write("CASTRA")
  turtle.right(30)
  turtle.back(100)
  turtle.dot(12)
  turtle.write("MARAKK")
  turtle.right(340)
  turtle.back(120)
  turtle.dot(12)
  turtle.write("BATEN ALGIEDI")
  turtle.right(270)
  turtle.back(40)
  turtle.dot(8)
  turtle.right(356)
  turtle.back(175)
  turtle.dot(10)
  turtle.write("DABIH")
  turtle.right(360)
  turtle.back(60)

  time.sleep(5)
  turtle.reset()
  turtle.color('white')
  turtle.penup()
  turtle.goto(0,0)
  turtle.dot(12)
  turtle.write("   Armus")
  turtle.pendown()
  turtle.penup()
  turtle.goto(150,180)
  turtle.pendown()
  turtle.dot(12)
  turtle.write("ALGIEDI")
  turtle.right(330)
  turtle.back(20)
  turtle.dot(10)
  turtle.write("--------ALSHAT")
  turtle.back(160)
  turtle.dot(12)
  turtle.write("DORSUM")
  turtle.right(30)
  turtle.back(120)
  turtle.dot(12)
  turtle.write("NASHIRA")
  turtle.right(10)
  turtle.back(40)
  turtle.dot(12)
  turtle.write("DENEB ALGEDI")
  turtle.right(240)
  turtle.back(50)
  turtle.dot(8)
  turtle.right(305)
  turtle.back(20)
  turtle.dot(12)
  turtle.write("CASTRA")
  turtle.right(30)
  turtle.back(100)
  turtle.dot(12)
  turtle.write("MARAKK")
  turtle.right(340)
  turtle.back(120)
  turtle.dot(12)
  turtle.write("BATEN ALGIEDI")
  turtle.right(270)
  turtle.back(40)
  turtle.dot(8)
  turtle.right(356)
  turtle.back(175)
  turtle.dot(10)
  turtle.write("DABIH")
  turtle.right(360)
  turtle.back(60)

  

fourthPage()
time.sleep(5)
window.clear()